import {
  Facebook,
  Instagram,
  MonitorSmartphone,
  Handshake,
  Megaphone,
  MapPin,
  Phone,
  MoreHorizontal,
} from "lucide-react";

export const source = [
  { label: "Facebook", value: "Facebook", icon: Facebook },
  { label: "Instagram", value: "Instagram", icon: Instagram },
  { label: "Advertisement", value: "Advertisement", icon: MonitorSmartphone },
  { label: "Sales", value: "Sales", icon: Handshake },
  { label: "Marketing", value: "Marketing", icon: Megaphone },
  { label: "Visit", value: "Visit", icon: MapPin },
  { label: "Call", value: "Call", icon: Phone },
  { label: "Other", value: "Other", icon: MoreHorizontal },
];

export const staff = [
  {
    label: "Don Lee",
    value: "Don Lee",
  },
  {
    label: "John Kim",
    value: "John Kim",
  },
  {
    label: "Sophia Lee",
    value: "Sophia Lee",
  },
];

export const productsOptions = [
  { label: "Bed", value: "1" },
  { label: "Sofa", value: "2" },
  { label: "Dining Table", value: "3" },
  { label: "Chair", value: "4" },
  { label: "Wardrobe", value: "5" },
  { label: "Coffee Table", value: "6" },
  { label: "Bookshelf", value: "7" },
  { label: "TV Stand", value: "8" },
  { label: "Office Desk", value: "9" },
  { label: "Nightstand", value: "10" },
];

export const followupStatus = [
   { label: "New", value: "New", color: "#f89705ff" },
  { label: "Audit", value: "Measurement", color: "#34badbff" },
  { label: "ICV", value: "Proposals", color: "#f1c40f" },
  { label: "Valuation", value: "Project Confirmation", color: "#95a5a6" },
  { label: "Tax", value: "Followup", color: "#2ecc71" },
  // { label: "Lost", value: "Lost", color: "#020101ff" },
];

export const priority = [
  { label: "Cool", value: 1 },
  { label: "Warm", value: 2 },
  { label: "Hot", value: 3 },
];

export const tableData = [
  {
    dateDisplay: "2024-01-12",
    time: "20:00:00",
    custId: "CS0001",
    name: "John Doe",
    mobile: "9187625768",
    email: "john.doe@example.com",
    assigned: "Don Lee",
    status: ["New"],
    addedBy: "Don Lee",
    source: "Facebook",
    _id: "one",
  },
  {
    dateDisplay: "2024-02-15",
    time: "14:30:00",
    custId: "CS0002",
    name: "Jane Smith",
    mobile: "9178896543",
    email: "jane.smith@example.com",
    assigned: "Anna Brown",
    status: ["Processing"],
    addedBy: "Anna Brown",
    source: "Instagram",
  },
  {
    dateDisplay: "2024-03-05",
    time: "09:15:00",
    custId: "CS0003",
    name: "Robert Wilson",
    mobile: "9198765432",
    email: "robert.wilson@example.com",
    assigned: "Mike Chan",
    status: ["Closed"],
    addedBy: "Mike Chan",
    source: "Twitter",
  },
  {
    dateDisplay: "2024-04-22",
    time: "11:45:00",
    custId: "CS0004",
    name: "Emily Davis",
    mobile: "9187654321",
    email: "emily.davis@example.com",
    assigned: "Sophia Lee",
    status: ["Payment"],
    addedBy: "Sophia Lee",
    source: "Facebook",
  },
  {
    dateDisplay: "2024-05-10",
    time: "16:20:00",
    custId: "CS0005",
    name: "Michael Brown",
    mobile: "9176543210",
    email: "michael.brown@example.com",
    assigned: "John Kim",
    status: ["Follow Up"],
    addedBy: "John Kim",
    source: "Facebook",
  },
  {
    dateDisplay: "2024-06-18",
    time: "13:10:00",
    custId: "CS0006",
    name: "Olivia Johnson",
    mobile: "9191234567",
    email: "olivia.johnson@example.com",
    assigned: "Anna Brown",
    status: ["Pending"],
    addedBy: "Anna Brown",
    source: "Instagram",
  },
  {
    dateDisplay: "2024-07-25",
    time: "10:05:00",
    custId: "CS0007",
    name: "William Martinez",
    mobile: "9189012345",
    email: "william.martinez@example.com",
    assigned: "Mike Chan",
    status: ["Processing"],
    addedBy: "Mike Chan",
    source: "Facebook",
  },
  {
    dateDisplay: "2024-08-30",
    time: "15:40:00",
    custId: "CS0008",
    name: "Ava Garcia",
    mobile: "9181122334",
    email: "ava.garcia@example.com",
    assigned: "Sophia Lee",
    status: ["Closed"],
    addedBy: "Sophia Lee",
    source: "Thread",
  },
  {
    dateDisplay: "2024-09-12",
    time: "12:25:00",
    custId: "CS0009",
    name: "James Anderson",
    mobile: "9174455667",
    email: "james.anderson@example.com",
    assigned: "Don Lee",
    status: ["Converted"],
    addedBy: "Don Lee",
    source: "Call",
  },
  {
    dateDisplay: "2024-10-03",
    time: "17:55:00",
    custId: "CS0010",
    name: "Sophia Thomas",
    mobile: "9199988776",
    email: "sophia.thomas@example.com",
    assigned: "John Kim",
    status: ["Payment"],
    addedBy: "John Kim",
    source: "Facebook",
  },
  {
    dateDisplay: "2024-11-19",
    time: "08:35:00",
    custId: "CS0011",
    name: "Daniel Lee",
    mobile: "9187654320",
    email: "daniel.lee@example.com",
    assigned: "Anna Brown",
    status: ["New"],
    addedBy: "Anna Brown",
    source: "Call",
  },
  {
    dateDisplay: "2024-12-27",
    time: "19:15:00",
    custId: "CS0012",
    name: "Mia White",
    mobile: "9177788990",
    email: "mia.white@example.com",
    assigned: "Mike Chan",
    status: ["Processing"],
    addedBy: "Mike Chan",
    source: "Instagram",
  },
  {
    dateDisplay: "2025-01-05",
    time: "10:50:00",
    custId: "CS0013",
    name: "Logan Harris",
    mobile: "9192345678",
    email: "logan.harris@example.com",
    assigned: "Don Lee",
    status: ["Follow Up"],
    addedBy: "Don Lee",
    source: "Facebook",
  },
  {
    dateDisplay: "2025-02-11",
    time: "14:05:00",
    custId: "CS0014",
    name: "Isabella Clark",
    mobile: "9183456789",
    email: "isabella.clark@example.com",
    assigned: "Sophia Lee",
    status: ["Closed"],
    addedBy: "Sophia Lee",
    source: "Twitter",
  },
  {
    dateDisplay: "2025-03-22",
    time: "09:35:00",
    custId: "CS0015",
    name: "Lucas Robinson",
    mobile: "9198761234",
    email: "lucas.robinson@example.com",
    assigned: "John Kim",
    status: ["Pending"],
    addedBy: "John Kim",
    source: "Facebook",
  },
  {
    dateDisplay: "2025-04-16",
    time: "11:25:00",
    custId: "CS0016",
    name: "Charlotte Lewis",
    mobile: "9189988776",
    email: "charlotte.lewis@example.com",
    assigned: "Anna Brown",
    status: ["Payment"],
    addedBy: "Anna Brown",
    source: "Twitter",
  },
  {
    dateDisplay: "2025-05-20",
    time: "16:45:00",
    custId: "CS0017",
    name: "Henry Walker",
    mobile: "9176655443",
    email: "henry.walker@example.com",
    assigned: "Mike Chan",
    status: ["Processing"],
    addedBy: "Mike Chan",
    source: "Facebook",
  },
  {
    dateDisplay: "2025-06-28",
    time: "13:30:00",
    custId: "CS0018",
    name: "Amelia Hall",
    mobile: "9182233445",
    email: "amelia.hall@example.com",
    assigned: "Sophia Lee",
    status: ["Converted"],
    addedBy: "Sophia Lee",
    source: "Thread",
  },
  {
    dateDisplay: "2025-07-04",
    time: "15:10:00",
    custId: "CS0019",
    name: "Sebastian Allen",
    mobile: "9173344556",
    email: "sebastian.allen@example.com",
    assigned: "John Kim",
    status: ["New"],
    addedBy: "John Kim",
    source: "Facebook",
  },
  {
    dateDisplay: "2025-08-09",
    time: "18:20:00",
    custId: "CS0020",
    name: "Harper Young",
    mobile: "9195566778",
    email: "harper.young@example.com",
    assigned: "Don Lee",
    status: ["Closed"],
    addedBy: "Don Lee",
    source: "Facebook",
  },
];